<a href="https://colab.research.google.com/github/mahbubpatwari/DemoApp/blob/main/Earlyfirst_part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
os.makedirs("data", exist_ok=True)
os.makedirs("results", exist_ok=True)
print("Folders created!")

Folders created!


In [ ]:
!python prepare_data.py --input dataset.csv --outdir data

Split sizes: 13981 2996 2997
train {0: 0.2667906444460339, 1: 0.3088477219083041, 2: 0.3307345683427509, 3: 0.0936270653029111}
val {0: 0.2666889185580774, 1: 0.30874499332443256, 2: 0.3307743658210948, 3: 0.0937917222963952}
test {0: 0.2669336002669336, 1: 0.3089756423089756, 2: 0.330663997330664, 3: 0.09342676009342676}


In [ ]:
import pandas as pd
df = pd.read_csv("dataset.csv")
for label in sorted(df["Label"].unique()):
    print(f"--- Label {label} ---")
    print(df[df["Label"] == label]["Sentence"].iloc[0])
    print(df[df["Label"] == label]["Sentence"].iloc[1])
    print()

--- Label 0 ---
Mugdho hoye dekhlam, jano mone holo ekta short feature film. Shesh hoye jawar poreo ekta brilliant aftereffect shubhro babu, how about venturing into feature film creation? ekta production house shuru korei falo, guaranteed success
Pray 5yrs eisob jaygar samne die daily jatayat korechi bari theke bus e matro 30mins er durotto. Eisob hidden gem kokhobo kheyal e korini

--- Label 1 ---
Potombar je barite asbe tar vuter voye hatfel nisoi hobe
Poco nam er sathai kolongko laiga asa

--- Label 2 ---
Tecno camon 20, redmi note 12 and inifinix note 30. Konta kinbo? khub confusing e achi. Plz keu help koiren
Pottek ta video kobe shoot kore hoyeche oii ta video te deye dele vlo hoy

--- Label 3 ---
Youtube ar volg gula boring hoia jaitase din din. Onk din por ai volg ta dakhe val laglo
Your video making, camera work is really good. I think, if you wear a colored rubber gloves while showing the installation of parts, then it will look more freshclean. Dont take it other way but sh

In [ ]:
!python train_svm.py

SVM Accuracy: 0.706373039706373
SVM Macro F1: 0.6869628385492661
SVM Mixed-class F1: 0.5951417004048583
              precision    recall  f1-score   support

    Positive       0.74      0.73      0.73       800
    Negative       0.71      0.73      0.72       926
     Neutral       0.69      0.71      0.70       991
       Mixed       0.69      0.53      0.60       280

    accuracy                           0.71      2997
   macro avg       0.70      0.68      0.69      2997
weighted avg       0.71      0.71      0.71      2997

Confusion matrix:
 [[583  62 129  26]
 [ 74 679 149  24]
 [100 166 708  17]
 [ 36  51  46 147]]


In [ ]:
!python train_lstm.py

Epoch 1/8 - loss: 1.3072
Epoch 2/8 - loss: 1.3023
Epoch 3/8 - loss: 1.2991
Epoch 4/8 - loss: 1.2960
Epoch 5/8 - loss: 1.2946
Epoch 6/8 - loss: 1.2934
Epoch 7/8 - loss: 1.2931
Epoch 8/8 - loss: 1.2924
LSTM Accuracy: 0.335669002335669
LSTM Macro F1: 0.13655918559608318
LSTM Mixed-class F1: 0.014084507042253521
Confusion matrix:
 [[  1   7 792   0]
 [  0  14 910   2]
 [  0   2 989   0]
 [  3   3 272   2]]


In [ ]:
!python train_lstm.py

Epoch 1/10 - loss: 1.0565
Epoch 2/10 - loss: 0.7660
Epoch 3/10 - loss: 0.5666
Epoch 4/10 - loss: 0.4027
Epoch 5/10 - loss: 0.2616
Epoch 6/10 - loss: 0.1629
Epoch 7/10 - loss: 0.0969
Epoch 8/10 - loss: 0.0630
Epoch 9/10 - loss: 0.0394
Epoch 10/10 - loss: 0.0266
LSTM Accuracy: 0.6332999666333
LSTM Macro F1: 0.6087063377184082
LSTM Mixed-class F1: 0.4943820224719101
Confusion matrix:
 [[584  73 104  39]
 [144 614 119  49]
 [203 186 568  34]
 [ 62  49  37 132]]


In [ ]:
!pip install -q transformers

In [ ]:
!python train_bert.py --mode baseline


tokenizer_config.json: 100% 48.0/48.0 [00:00<00:00, 232kB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 917kB/s]
tokenizer.json: 100% 466k/466k [00:00<00:00, 1.03MB/s]
config.json: 100% 570/570 [00:00<00:00, 2.71MB/s]

model.safetensors: downloading bytes:  84% 368M/440M [00:02<00:00, 302MB/s, 31.2MB/s  ]
model.safetensors: downloading bytes:  93% 410M/440M [00:02<00:00, 262MB/s, 36.0MB/s  ]
model.safetensors: reconstructing file:  76% 335M/440M [00:03<00:00, 125MB/s, 18.9MB/s  ]
model.safetensors: downloading bytes: 100% 415M/415M [00:05<00:00, 78.1MB/s, 37.2MB/s  ]
model.safetensors: reconstructing file: 100% 440M/440M [00:05<00:00, 82.8MB/s, 34.4MB/s  ]
Loading weights: 100% 199/199 [00:00<00:00, 5595.25it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.transfo

In [ ]:
!python train_bert.py --mode class_weight

python3: can't open file '/content/train_bert.py': [Errno 2] No such file or directory


In [ ]:
import os
os.makedirs("data", exist_ok=True)
os.makedirs("results", exist_ok=True)
print("Folders created!")

Folders created!


In [ ]:
!python prepare_data.py --input dataset.csv --outdir data

Split sizes: 13981 2996 2997
train {0: 0.2667906444460339, 1: 0.3088477219083041, 2: 0.3307345683427509, 3: 0.0936270653029111}
val {0: 0.2666889185580774, 1: 0.30874499332443256, 2: 0.3307743658210948, 3: 0.0937917222963952}
test {0: 0.2669336002669336, 1: 0.3089756423089756, 2: 0.330663997330664, 3: 0.09342676009342676}


In [ ]:
!pip install -q transformers

In [ ]:
!python train_bert.py --mode class_weight

tokenizer_config.json: 100% 48.0/48.0 [00:00<00:00, 172kB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 2.95MB/s]
tokenizer.json: 100% 466k/466k [00:00<00:00, 7.00MB/s]
config.json: 100% 570/570 [00:00<00:00, 2.80MB/s]

model.safetensors: downloading bytes:  60% 263M/440M [00:01<00:00, 270MB/s, 23.1MB/s  ]
model.safetensors: downloading bytes:  69% 303M/440M [00:01<00:00, 233MB/s, 26.8MB/s  ]
model.safetensors: downloading bytes:  93% 411M/440M [00:02<00:00, 220MB/s, 35.4MB/s  ]
model.safetensors: downloading bytes: 100% 415M/415M [00:02<00:00, 149MB/s, 36.9MB/s  ]
model.safetensors: reconstructing file: 100% 440M/440M [00:02<00:00, 158MB/s, 39.8MB/s  ]
Loading weights: 100% 199/199 [00:00<00:00, 5760.85it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED | 
cls.predictions.transform.

In [ ]:
!python train_bert.py --mode oversample

Loading weights: 100% 199/199 [00:00<00:00, 5305.70it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.seq_relationship.weight                | UNEXPECTED | 
classifier.weight                          | MISSING    | 
classifier.bias                            | MISSING    | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider

In [ ]:

import os
os.makedirs("data", exist_ok=True)
os.makedirs("results", exist_ok=True)
print("Folders created!")



Folders created!


In [ ]:
!python prepare_data.py --input dataset.csv --outdir data



Split sizes: 13981 2996 2997
train {0: 0.2667906444460339, 1: 0.3088477219083041, 2: 0.3307345683427509, 3: 0.0936270653029111}
val {0: 0.2666889185580774, 1: 0.30874499332443256, 2: 0.3307743658210948, 3: 0.0937917222963952}
test {0: 0.2669336002669336, 1: 0.3089756423089756, 2: 0.330663997330664, 3: 0.09342676009342676}


In [ ]:
!pip install -q transformers

In [ ]:
!python train_bert.py --mode oversample


tokenizer_config.json: 100% 48.0/48.0 [00:00<00:00, 196kB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 5.08MB/s]
tokenizer.json: 100% 466k/466k [00:00<00:00, 18.8MB/s]
config.json: 100% 570/570 [00:00<00:00, 3.33MB/s]

model.safetensors: downloading bytes:  63% 277M/440M [00:01<00:00, 227MB/s, 25.0MB/s  ]
model.safetensors: downloading bytes:  90% 395M/440M [00:01<00:00, 235MB/s, 34.2MB/s  ]
model.safetensors: downloading bytes: 100% 415M/415M [00:02<00:00, 178MB/s, 37.1MB/s  ]
model.safetensors: reconstructing file: 100% 440M/440M [00:02<00:00, 189MB/s, 40.6MB/s  ]
Loading weights: 100% 199/199 [00:00<00:00, 7249.40it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED

# New Section

In [ ]:
import os
os.makedirs("data", exist_ok=True)
os.makedirs("results", exist_ok=True)
print("Folders created!")

Folders created!


In [ ]:
!python prepare_data.py --input dataset.csv --outdir data

Split sizes: 13981 2996 2997
train {0: 0.2667906444460339, 1: 0.3088477219083041, 2: 0.3307345683427509, 3: 0.0936270653029111}
val {0: 0.2666889185580774, 1: 0.30874499332443256, 2: 0.3307743658210948, 3: 0.0937917222963952}
test {0: 0.2669336002669336, 1: 0.3089756423089756, 2: 0.330663997330664, 3: 0.09342676009342676}


In [ ]:
!pip install -q transformers

In [ ]:
!python train_bert.py --mode focal

tokenizer_config.json: 100% 48.0/48.0 [00:00<00:00, 200kB/s]
vocab.txt: 100% 232k/232k [00:00<00:00, 8.98MB/s]
tokenizer.json: 100% 466k/466k [00:00<00:00, 17.9MB/s]
config.json: 100% 570/570 [00:00<00:00, 1.95MB/s]

model.safetensors: downloading bytes:  69% 303M/440M [00:01<00:00, 307MB/s, 25.0MB/s  ]
model.safetensors: downloading bytes:  88% 390M/440M [00:02<00:00, 239MB/s, 35.1MB/s  ]
model.safetensors: downloading bytes: 100% 415M/415M [00:06<00:00, 65.1MB/s, 37.1MB/s  ]
model.safetensors: reconstructing file: 100% 440M/440M [00:06<00:00, 69.0MB/s, 36.7MB/s  ]
Loading weights: 100% 199/199 [00:00<00:00, 6296.95it/s]
[transformers] BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECT

In [ ]:
!python train_bert.py --mode focal


In [ ]:
import torch
print("CUDA available:", torch.cuda.is_available())

In [ ]:
import torch
print("CUDA available:", torch.cuda.is_available())